config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  get "books/search", to: "books#search"
  get "authors/search", to: "authors#search"
  get "users/login", to: "users#login"
  post "users/login", to: "users#logging"
  get "users/logout", to: "users#logout"
  get "users/search", to: "users#search"
  post "friends/:id/add", to: "friends#add"
  post "friends/:id/remove", to: "friends#remove"

  resources :genres, only: [:index, :show]
  resources :authors, only: [:index, :show]
  resources :users
  resources :books, only: [:index, :show, :new, :create]
  resources :ratings, only: [:new, :create, :edit, :update, :destroy]

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  has_many :ratings, through: :books

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :genre
  has_many :ratings
  has_many :users, through: :ratings

  validates_presence_of :name, :author_id, :genre_id
  validates :name, uniqueness: {scope: :author_id, case_sensitive: false}
  def average_rating
    self.ratings.average(:amount).to_f.round(2)
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_presence_of :user_id, :friend_id
  validates_uniqueness_of :user_id, scope: :friend_id
end

app/models/frienship.rb
class Frienship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_presence_of :user_id, :friend_id
  validates_uniqueness_of :user_id, scope: :friend_id
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
  delegate :author, to: :book

  validates_presence_of :amount, :user_id, :book_id
  validates_uniqueness_of :user_id, scope: :book_id
end

app/models/search.rb
class Search

  def self.for(s_type: s_type, name: name)
    s_type.where("name like ?", "%#{name}%")
  end

  def self.users(name)
    results = User.where("username like ?", "%#{name}%")
    results << User.where("name like ?", "%#{name}%")
    results.flatten.uniq
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ratings
  has_many :books, through: :ratings
  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_secure_password
  validates_presence_of :name, :username
  validates :username, uniqueness: {case_sensitive: false}

  def mutual_friends
    friends + inverse_friends
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all.sort_by {|author| author.name}
  end

  def show
    @author = Author.find(params[:id])
  end

  def search
    search_term = params[:keyword]
    authors = Author.where("lower(name) = ?", search_term.downcase)
    if authors.length == 1
      redirect_to authors.first
    else
      @authors = Search.for(s_type: Author, name: search_term).sort_by {|author| author.name}
      if @authors == []
        redirect_to authors_path, notice: "Sorry, couldn't find what you were looking for! Please try again."
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.sort_by {|book| [book.name, book.author.name]}
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    author = Author.find_or_create_by(name: params[:book][:authors][:name])
    genre = Genre.find_or_create_by(name: params[:book][:genres][:name])
    @book = Book.new(name: params[:book][:name], genre_id: genre.id, author_id: author.id)
    if @book.save
      redirect_to @book, notice: "Book successfully created!"
    else
      render :new
    end
  end

  def search
    search_term = params[:keyword]
    books = Book.where("lower(name) = ?", search_term.downcase)
    if books.length == 1
      redirect_to books.first
    elsif books.length != 0
      @books = books.sort_by {|book| book.author.name}
    else
      @books = Search.for(s_type: Book, name: search_term).sort_by {|book| [book.name, book.author.name]}
      if @books == []
        redirect_to books_path, notice: "Sorry, couldn't find what you were looking for! Please try again."
      end
    end
  end


end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def add
    Friendship.create(user_id: current_user.id, friend_id: params[:id])
    redirect_to User.find(params[:id]), notice: "Friend added!"
  end

  def remove
    friend = Friendship.find_by(user_id: current_user.id, friend_id: params[:id])
    friend.destroy
    redirect_to User.find(params[:id]), notice: "Friend removed."
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.sort_by {|genre| genre.name}
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @rating = Rating.new
  end

  def create
    @rating = Rating.new(amount: params[:rating], user_id: current_user.id, book_id: params[:book_id])
    @rating.save
    redirect_to Book.find(params[:book_id]), notice: "Rating successful!"
  end

  def edit
    @rating = Rating.find(params[:id])
  end

  def update
    @rating = Rating.find(params[:id])
    @rating.update(amount: params[:rating][:amount])
    redirect_to @rating.book
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to books_path, notice: "Rating successfully deleted."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.sort_by {|user| user.username.downcase}
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Account created!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to @user
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      if params[:user][:password]
        redirect_to @user, notice: "Password successfully changed!"
      elsif params[:user][:bio]
        redirect_to @user, notice: "Account info successfully updated!"
      end
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Account successfully deleted."
  end

  def search
    search_term = params[:keyword]
    if user = User.find_by(username: search_term)
      redirect_to user
    else
      @users = Search.users(search_term).sort_by {|user| user.username}
        if @users == []
          redirect_to users_path, notice: "Sorry, couldn't find what you were looking for! Please try again."
        end
    end
  end

  def login
    session[:return_to] = request.referer
    @user = User.new
  end

  def logging
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to session.delete(:return_to)
    else
      flash[:error] = "Something went wrong! Please check your username and password and try again."
      redirect_to users_login_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path, notice: "You have been successfully logged out."
  end

private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation, :bio)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>
<%= notice %>
<%= form_tag("authors/search", method: "get") do %>
  <%= label_tag(:keyword, "Search Authors:") %>
  <%= text_field_tag(:keyword, nil, list: "titles", size: "25") %>
    <datalist id="titles">
      <% Author.all.each do |author| %>
        <option value="<%=author.name%>">
          <% end %>
    </datalist>
  <%= submit_tag("Search") %>
<% end %>

<h3>Browse All:</h3>
<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author %></li>
  <% end %>
</ul>

app/views/authors/search.html.erb
<h1>Did you mean...?</h1>

<ul>
  <% @authors.each do |author| %>
    <li><%= link_to author.name, author %> </li>
  <% end %>
</ul>

app/views/authors/show.html.erb
<h1><%=@author.name%></h1>

<h2>Top Rated</h2>
<ol>
  <% books = @author.books.sort_by {|book| [-(Rating.where(book_id: book.id).average(:amount) || 0), book.name] } %>
  <% books.each do |book| %>
    <li><em><%=link_to book.name, book%></em> - <%= link_to book.genre.name, book.genre %> - <strong>Average Rating: <%=book.average_rating%>/10</strong></li>
  <% end %>
</ol>

app/views/books/index.html.erb
<h1>Books</h1>
<%= notice %>
<%= form_tag("books/search", method: "get") do %>
  <%= label_tag(:keyword, "Search Titles:") %>
  <%= text_field_tag(:keyword, nil, list: "titles", size: "35") %>
    <datalist id="titles">
      <% Book.all.map do |book| book.name end.uniq.each do |book| %>
        <option value="<%=book%>">
          <% end %>
    </datalist>
  <%= submit_tag("Search") %>
<% end %>

<br>Can't find what you're looking for? <%= link_to "Create a new book!", new_book_path %>

<h3>Browse All:</h3>
<ul>
  <% @books.each do |book| %>
  <li><em><%=link_to book.name, book%></em> by <%= link_to book.author.name, book.author %>, <%= link_to book.genre.name, book.genre %> - <strong>Average Rating: <%= book.average_rating %></strong></li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h1>New Book</h1>

<% if @book.errors.any? %>
Whoops! Looks like <%= pluralize(@book.errors.count, "error") %> prevented this book from saving:
<% @book.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>
<% end %>

<%= form_for @book do |f| %>
  <%= f.label :name, "Title" %>
  <%= f.text_field :name %><br>
  <%= f.fields_for :authors do |authors_form| %>
    <%= authors_form.label :name, "Author" %>
    <%= authors_form.text_field :name, list: "authors" %>
    <datalist id="authors">
      <% Author.all.each do |author| %>
      <option value="<%=author.name%>">
    <% end %>
    </datalist>
  <% end %><br>

  <%= f.fields_for :genres do |genres_form| %>
    <%= genres_form.label :name, "Genre" %>
    <%= genres_form.text_field :name, list: "genres" %>
    <datalist id="genres">
      <% Genre.all.each do |genre| %>
      <option value="<%=genre.name%>">
    <% end %>
    </datalist>
  <% end %><br><br>

<%= f.submit "Create New Book", data: {confirm: "Please double-check book info! A book cannot be edited after creation."} %>


<% end %>

app/views/books/search.html.erb
<h1>Did you mean...?</h1>

<ul>
  <% @books.each do |book| %>
    <li><%= link_to book.name, book %> by <%=link_to book.author.name, book.author%>, <%=link_to book.genre.name, book.genre%></li>
  <% end %>
</ul>

app/views/books/show.html.erb
<br><br>
<%= notice %>
<h1><%=@book.name%></h1>

<h2>Author: <%=link_to @book.author.name, @book.author %></h2>

<h2>Genre: <%=link_to @book.genre.name, @book.genre%></h2>

<h2>Average Rating: <%=@book.average_rating%></h2>

<%= notice %><br>
<% if logged_in? %>
  <% if current_user.books.include? @book %>
  <% rating = @book.ratings.find_by(user_id: current_user.id) %>
    <strong>Your Rating: <%= link_to rating.amount, edit_rating_path(rating) %> </strong><br>
    <%= link_to "Delete Rating", rating_path(rating), method: "delete", data: {confirm: "Are you sure you want to delete this rating?"} %><br>

    <% else %>
      Rate this book:
      <%= form_tag(ratings_path, method: "post") do  %>
        <%= hidden_field_tag :book_id, @book.id %>
        <%= select_tag :rating, options_for_select(1..10) %>
        <%= submit_tag "Rate!" %>
      <% end %>
    <% end %>

<% else %>
<%= link_to "SIGN UP", new_user_path %> or <%= link_to "LOG IN", users_login_path %> to rate this book!
<% end %>

app/views/genres/index.html.erb
<h1>Genres</h1>

<ul>
  <% @genres.each do |genre| %>
  <li><%=link_to genre.name, genre%></li>
  <% end %>
</ul>

app/views/genres/show.html.erb
<h1><%=@genre.name%></h1>

<h2>Top Rated</h2>
<ol>
  <% books = @genre.books.sort_by {|book| [-(Rating.where(book_id: book.id).average(:amount) || 0), book.name, book.author.name] } %>
  <% books.each do |book| %>
    <li><em><%= link_to book.name, book%></em> by <%= link_to book.author.name, book.author %>, <strong>Rated: <%= book.average_rating %>/10</strong></li>
  <% end %>
</ol>

app/views/ratings/destroy.html.erb
<h1>Ratings#destroy</h1>
<p>Find me in app/views/ratings/destroy.html.erb</p>

app/views/ratings/edit.html.erb
<h1>Edit Rating</h1>

<h3><%=@rating.book.name%></h3>
<h4>By <%=@rating.author.name%></h4>
<%= form_for @rating do |f| %>
  <%= f.select :amount, ((1..10).map {|i| [i,i]}) %>
  <%= f.submit %>
<% end %>

app/views/ratings/update.html.erb
<h1>Ratings#update</h1>
<p>Find me in app/views/ratings/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Profile for <%= @user.username %></h1>

<% if @user.errors.any? %>
Whoops! <%= @user.errors.full_messages.first %>
<% end %>

<h3>Update Name and/or Bio:</h3>
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :bio %>
<%= f.text_area :bio %><br>
<%= f.submit "Update!" %>
<% end %>

<h3>Change Password:</h3>
<%= form_for @user do |f| %>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br>
<%= f.submit "Change Password" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<%= notice %>

<%= form_tag("users/search", method: "get") do %>
  <%= label_tag(:keyword, "Search Users by Name or Username:") %>
  <%= text_field_tag(:keyword) %>
  <%= submit_tag("Search") %>
<% end %>


<h3>Browse all:</h3>
<ul>
  <% @users.each do |user| %>
  <li><%=link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/login.html.erb
<h1>Log in!</h1>

<%= flash[:error] if flash[:error] %>



<%= form_for(@user, url: "login", method: "post") do |f| %>
<%= f.label :username %>
<%= f.text_field :username %><br>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit "Log In" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<% if @user.errors.any? %>
Whoops! Looks like <%= pluralize(@user.errors.count, "error") %> prevented you from signing up:
<% @user.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :username %>
<%= f.text_field :username %><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br>
<%= f.submit "Sign Up" %>
<% end %>

app/views/users/search.html.erb
<h1>Did you mean...?</h1>

<ul>
  <% @users.each do |user| %>
    <li><%=link_to user.username, user%> - <%=user.name%></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% if current_user == @user %>

<h1>Welcome, <%= current_user.name %>!</h1>
<%= notice %><br>
<%= link_to "Rate a new book!", books_path %><br>
<%= link_to "Edit Profile", edit_user_path(@user) %><br>
<%= link_to "Delete Account", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete your account? This action cannot be reversed!!!"} %><br>

<% else %>


<h1><%=@user.name%> (<%= @user.username %>)</h1>
<% if logged_in? %>
<%= notice %>
  <% if current_user.friends.include? @user %>
    <%= form_tag "/friends/#{@user.id}/remove", method: "post" do %>
    <%= submit_tag "Remove Friend" %>
    <% end %>
  <% else %>
    <%= form_tag "/friends/#{@user.id}/add", method: "post" do %>
    <%= submit_tag "Add Friend" %>
    <% end %>
  <% end %>
  <% end %>
<% end %>
<% if @user.bio && @user.bio != "" %>
<h2>Bio:</h2>
<%= @user.bio %>

<% else %>
  <% if current_user == @user %>
  <br><br>
  <strong>Your bio is blank! Why don't you <%= link_to "add something to it?!", edit_user_path%></strong>
  <% end %>
<% end %>

<h3>Recently Rated</h3>
<ul>
      <%@user.ratings.order('updated_at DESC').limit(5).each do |rating| %>
      <li><em><%=link_to rating.book.name, rating.book%></em> by <%=link_to rating.author.name, rating.author%> - <strong><%=current_user == @user ? (link_to rating.amount, edit_rating_path(rating)) : rating.amount%></strong></li>
      <% end %>
    </ul>

<h3>Top Rated </h3>
<ul>
  <%@user.ratings.order('amount DESC, updated_at DESC').each do |rating| %>
  <li><em><%=link_to rating.book.name, rating.book%></em> by <%=link_to rating.author.name, rating.author%> - <strong><%=current_user == @user ? (link_to rating.amount, edit_rating_path(rating)) : rating.amount%></strong></li>
  <% end %>
</ul>

<% if @user.friends != []%>
<h3>Friends</h3>
  <ul>
    <% @user.friends.sort_by do |friend|friend.username end.each do |friend| %>
      <li><%=link_to friend.username, friend %></li>
    <% end %>
  </ul>
<% end %>
<% if @user.inverse_friends != []%>
<h3>Followers</h3>
  <ul>
    <% @user.inverse_friends.sort_by do |follower| follower.username end.each do |follower| %>
      <li><%=link_to follower.username, follower%></li>
    <% end %>
  </ul>
<% end %>